name: Feature Request
description: Suggest an idea for Synology Download Station by R22E
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement / Use Case
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Proposed Behavior
      description: Describe the solution or functionality you'd like to see.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Alternatives / Context
      description: Any alternative solutions you've considered, or additional context.
